CREATE TABLE contact (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  person_id INT NOT NULL,
  name VARCHAR NOT NULL,
  role VARCHAR NOT NULL,
  phone VARCHAR NULL,
  email VARCHAR NULL,
  mail VARCHAR NULL
);
